In [1]:
import orflib as orf
import numpy as np
import os

print("orflib version: {0}".format(orf.version()))
print("pid: {0}".format(os.getpid()))

orflib version: 0.1.0-debug
pid: 13357


In [2]:
l = [np.array([1.]), np.array([1., 1.])]

for i in range(1,7):
    op = orf.polyProd(l[1], l[i])
    l.append(op)

In [3]:
l

[array([1.]),
 array([1., 1.]),
 array([1., 2., 1.]),
 array([1., 3., 3., 1.]),
 array([1., 4., 6., 4., 1.]),
 array([ 1.,  5., 10., 10.,  5.,  1.]),
 array([ 1.,  6., 15., 20., 15.,  6.,  1.]),
 array([ 1.,  7., 21., 35., 35., 21.,  7.,  1.])]